name: multiavatar
description: Multiavatar is a multicultural avatar maker.
version: 1.0.1
author: Iheb Briki<iheb@pixelium.tn>
homepage: https://github.com/X-SLAYER/Multiavatar

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
